# http -> https
map $http_x_forwarded_proto $fwd_proto {
    ""  $scheme;
    default $http_x_forwarded_proto;
}

map $http_x_forwarded_port $fwd_port {
    ""  $server_port;
    default $http_x_forwarded_port;
}

server {
    # port
    listen 80;
    server_name _;

    # 정적 파일 서빙 루트 디렉토리
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # http://3.34.173.34/api/ ---> http://board-back-end:8090/api/
    # reverse proxy 설정
    location /api/ {
        proxy_pass http://board-back-end:8090;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        # 거쳐온 프록시/클라이언트 IP 체인(감시용)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # 원래 요청의 스킴(http, https)
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    # http://back-end(:port)/oauth2/... 로 시작하는 요청에 대응하는 설정
    # http://back-end(:port)/login/oauth2/... 로 시작하는 요청에 대응하는 설정
    location ~^/(oauth2|login/oauth2) {
        proxy_pass http://board-back-end:8090;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        # 거쳐온 프록시/클라이언트 IP 체인(감시용)
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # 원래 요청의 스킴(http, https)
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 정적 파일 요청에 대응, .css 나 .js의 요청에 설정
    location ~* \.(css|js)$ {
        expires 5m;
        add_header Cache-Control "public";
    }

    location /assets/ {
        expires 5m;
        add_header Cache-Control "public";
    }
}

# docker 설치
# db(mysql설치) -> board schema
# vpc 설정

# build
# git / github

# ssh remote connect
# git clone(pull)
# docker compose build

